/**
 * Rol → yetki eşlemesi.
 * Her rolün sahip olduğu yetkileri tanımlar (RBAC temeli).
 */

import { ROLES, type Role } from "@/lib/auth/role-constants";
import { PERMISSIONS, type Permission } from "@/lib/auth/permissions";

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  // Kurucu (okul sahibi): okul içindeki her şeye yetkili (finans dahil).
  // Platform yönetimi (PLATFORM_MANAGE) hariç SCHOOL_ADMIN ile aynı kapsam.
  [ROLES.FOUNDER]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_WRITE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_CONFIGURE,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.SUBSCRIPTION_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_WRITE,
    PERMISSIONS.SCHEDULE_READ,
    PERMISSIONS.SCHEDULE_WRITE,
  ],
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_CONFIGURE,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.SUBSCRIPTION_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_WRITE,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_WRITE,
    PERMISSIONS.SCHEDULE_READ,
    PERMISSIONS.SCHEDULE_WRITE,
  ],
  // Müdür: okul gidişatı, öğretmenler, ders programı, CRM, duyurular —
  // ANCAK finans/ekonomik veriler (FINANCE_*) ve abonelik YOK.
  [ROLES.PRINCIPAL]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_WRITE,
    PERMISSIONS.SCHEDULE_READ,
    PERMISSIONS.SCHEDULE_WRITE,
  ],
  // Müdür yardımcısı: müdüre yakın yetkiler, finans/abonelik YOK.
  [ROLES.VICE_PRINCIPAL]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.SCHEDULE_READ,
    PERMISSIONS.SCHEDULE_WRITE,
  ],
  // Koordinatör: akademik koordinasyon — öğrenci, ders programı, duyuru.
  [ROLES.COORDINATOR]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.SCHEDULE_READ,
    PERMISSIONS.SCHEDULE_WRITE,
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.SCHEDULE_READ,
  ],
  [ROLES.PARENT]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.AI_USE,
    PERMISSIONS.SCHEDULE_READ,
  ],
  [ROLES.SUPPORT]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.SALES]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_WRITE,
  ],
  // Halkla ilişkiler: aday veli (CRM) ve duyuru iletişimi.
  [ROLES.PR]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_WRITE,
    PERMISSIONS.AI_USE,
  ],
  // Halk / genel kullanıcı: yalnızca halka açık içerik + kendi başvuruları.
  [ROLES.PUBLIC]: [
    PERMISSIONS.ANNOUNCEMENT_READ,
  ],
};
