/**
 * Rol → yetki eşlemesi.
 * Her rolün sahip olduğu yetkileri tanımlar (RBAC temeli).
 */

import { ROLES, type Role } from "@/lib/auth/role-constants";
import { PERMISSIONS, type Permission } from "@/lib/auth/permissions";

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_WRITE,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_CONFIGURE,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_WRITE,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.PARENT]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.SUPPORT]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.SALES]: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.SUBSCRIPTION_READ,
  ],
};
